### ISSUE TITLE
Swift Compiler Error Group

### ISSUE THREAD

**Issue by skiddi3** [mymonero/mymonero-app-ios#65]
**Error while building: No such module 'PKHUD'**
/Users/*user*/mymonero-app-ios/Modules/WalletWizard/ViewControllers/CreateWallet_ConfirmMnemonic_ViewController.swift:36:8: No such module 'PKHUD'

Any idea how to fix that?

**Comment by paulshapiro** [comment]
Hello, per the installation instructions, you need to do a 'pod install'

**Comment by skiddi3** [comment]
I did. Thats why I was asking how to fix it.

**Comment by paulshapiro** [comment]
This probably isn't an issue with the project but rather an issue with your dev env or workflow so in future I might close these sorts of questions, and so I would generally recommend popping into IRC for this sort of thing in the future so we can look at it more interactively. 

For now, if you didn't get an error on installation, ensure you're opening the .xcworkspace file rather than the .xcodeproj file per Cocoapods usage guidelines.
